### ISSUE TITLE
backend API for frontend use

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#55]
This is an umbrella issue for handling data requests from the React/Express browser-side app. Requests should be processed based on the users' privileges in Canvas.

Break the work down into the smallest assignable issue one can work on. If an issue is complex (40 hours), then create multiple epics under this issue.

Try estimating in terms of complexity using Zenhub estimation tools.

**Comment by pushyamig** [comment]
@jonespm, Please breakdown the work into smaller pieces. I am not assigning this all to you since I can very well see this can be done by multiple people.

**Comment by jonespm** [comment]
Thanks, not sure if I'll have time today to add everything we talked about. Here's what I'm thinking. None of this includes testing so that may increase the estimates if we add unit or integration tests for some of these steps, which might be nice for a few of them.

1 - Canvas API Design (Est 40-60 hours)
- [ ] Research loopback and design some simple API's to see if it's better for our needs (about 4-8 hours) 
- [ ] Provide definition and pseudocode for at least one API in framework in CCM code with no-op action (Not sure maybe 2-4 hours?)
- [ ] Provide definition and pseudocode for the remainder of Canvas API (10 methods so ~20-30 hours)
- [ ] Provide definitions and pseudocode for the API's that will require elevated job permissions (5 methods so ~10-15 hours)

2 - Canvas API Wrapper (Est. 20-40 hours?)
- [ ] Create a a wrapper module/class inside CCM that wraps a Canvas API.
- [ ] This will likely need to handle token renewals/db retrievals, pagination and other things the API library doesn't. (Unknown how long this will take, seems like a few days, I'd say 20-40 hours for this wrapper?)

Steps 1 & 2 can be done concurrently. Then the next 2 steps can also be done concurrently.

3 - Canvas API Implementation (Around 50 hours)
- [ ] Once the first 2 phases complete are implement one of the API's fully using the Canvas API wrapper (Probably about 4 hours)
- [ ] After, implement the rest of the API's (Probably about 40 hours)

4 - Elevated Job Implementation (Unknown estimate, will involve designing the process, likely a collaborative effort of 80+ hours?)
- [ ] Once all of the Canvas API's an elevated job API process will need to be designed
- [ ] This will likely involve inserting data into the database and having another process (Python?) that is running as a job process this data. This could also happen via other methods and still has to be designed.
- [ ] Provide feedback to the user that their job has completed.

**Comment by pushyamig** [comment]
I think this issue served the purpose, we are using the KTH library and we have good workflow in the BE. I am closing this.
