### ISSUE TITLE
Backend Readiness

### ISSUE THREAD

**Issue by pushyamig** [tl-its-umich-edu/canvas-course-manager-next#87]
This Epic is keeping track of the issues bare minimum backend setup to connect with the FE and vice versa.  Below is the list of items to fulfilled 

- [x] Canvas Oauth workflow i.e generate a Scoped token and manage it for next time 
- [x] Making a Canvas API calls and data fetching, this means any Canvas external Library integration. 
- [x] Refresh the Canvas Oauth token when expired
- [x] How to hold on to LTI launch information in the BE (Express-session)
- [x] FE strategy to hold secure the launch information once sent
- ~~BE remembers the user from launch once user is authenticated/Authorized~~

The last item is still an item to debate if we want to implement our own Authorization process using Passport and LTIJS not being our gate keeper, https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/139

**Comment by pushyamig** [comment]
We have one more issue to make this issue to mark as done. The PR https://github.com/tl-its-umich-edu/canvas-course-manager-next/pull/135 for that is also open. Good Progress!

**Comment by pushyamig** [comment]
I created the issue for item 6 in the list https://github.com/tl-its-umich-edu/canvas-course-manager-next/issues/139 and we can handle it there

**Comment by pushyamig** [comment]
We hit a major milestone with the finish of this issue!
